/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shuame_rootgenius_sdk_JniHelper */

#ifndef _Included_com_shuame_rootgenius_sdk_JniHelper
#define _Included_com_shuame_rootgenius_sdk_JniHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shuame_rootgenius_sdk_JniHelper
 * Method:    decrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_shuame_rootgenius_sdk_JniHelper_decrypt
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_shuame_rootgenius_sdk_JniHelper
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_shuame_rootgenius_sdk_JniHelper_encrypt
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
